async function testWebhookWithUnifiedSystem() {
  console.log('🌐 Testing Unified System via Webhook\n');

  const testCases = [
    {
      name: "Personal Question Test",
      message: "Are you a real person or a bot?",
      expected: "Should deflect gracefully"
    },
    {
      name: "Business Question Test", 
      message: "What's your commission rate?",
      expected: "Should defer to in-person discussion"
    },
    {
      name: "Co-broking Agreement Test",
      message: "Yes, I'm open to co-broking",
      expected: "Should ask for timeslots"
    },
    {
      name: "Edge Case Test",
      message: "🤖👋 Hello there! 你好",
      expected: "Should handle gracefully"
    }
  ];

  for (const testCase of testCases) {
    console.log(`\n📋 ${testCase.name}`);
    console.log(`📝 Message: "${testCase.message}"`);
    console.log(`🎯 Expected: ${testCase.expected}`);
    console.log('-'.repeat(50));

    try {
      const response = await fetch('http://localhost:3000/api/wa/webhook', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          event: 'message',
          session: 'default',
          payload: {
            id: `test_message_${Date.now()}`,
            timestamp: Math.floor(Date.now() / 1000),
            from: '6591051399@c.us',
            fromMe: false,
            body: testCase.message,
            hasMedia: false,
            ack: 1,
            vCards: [],
            _data: {
              id: {
                fromMe: false,
                remote: '6591051399@c.us',
                id: `test_message_${Date.now()}`,
                _serialized: `false_6591051399@c.us_test_message_${Date.now()}`
              },
              body: testCase.message,
              type: 'chat',
              timestamp: Math.floor(Date.now() / 1000),
              notifyName: 'Test Agent',
              from: '6591051399@c.us',
              to: '66803102230@c.us',
              self: 'out'
            }
          }
        })
      });

      if (response.ok) {
        const result = await response.json();
        console.log(`✅ Webhook Response: ${response.status} - ${JSON.stringify(result)}`);
      } else {
        console.log(`❌ Webhook Error: ${response.status} - ${response.statusText}`);
      }

      // Wait a moment between tests
      await new Promise(resolve => setTimeout(resolve, 2000));

    } catch (error) {
      console.log(`❌ Network Error: ${error}`);
    }
  }

  console.log('\n🔍 Check the server logs to see the AI responses generated by the unified system.');
  console.log('📊 All responses should be professional, contextual, and appropriate.');
}

testWebhookWithUnifiedSystem().catch(console.error);